# Generated by Django 3.0.3 on 2020-03-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=20)),
                ('To', models.CharField(max_length=255)),
                ('Body', models.TextField()),
                ('Importance', models.TextField(choices=[('High', 'High'), ('Low', 'Low'), ('Normal', 'Normal')])),
                ('Polarity', models.CharField(blank=True, max_length=10)),
                ('Sentiment', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
